
---
- name: Install Apache HTTP Server on n3 server
  hosts: n3
  become: true
  tasks:
    - name: Install httpd package
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes


...




