---
- name: Create /opt/devops directory and info.txt file
  hosts: all
  become: yes

  tasks:
    - name: Ensure /opt/devops directory exists
      file:
        path: /opt/devops
        state: directory
        mode: '0755'

    - name: Create info.txt with custom content
      copy:
        content: "Hello from Ansible!"
        dest: /opt/devops/info.txt
        mode: '0644'
...
